name: gt2_01
sha1: b8e5d9ea443c41ad7206882a4b8deb579c769948
options:
  basename: gt2_01
  target_path: ovl_bin/gt2_01.exe
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  create_asm_dependencies: True

  ld_script_path: autogen/gt2_01.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".text", ".rodata", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - ovr1_symbol_addrs.txt
  reloc_addrs_path:
    - ovr1_reloc_addrs.txt

  undefined_funcs_auto_path: autogen/ovr1_undefined_funcs_auto.txt
  undefined_syms_auto_path: autogen/ovr1_undefined_syms_auto.txt
  create_undefined_syms_auto: True

  pair_rodata_to_text: True
  migrate_rodata_to_functions: True

  check_consecutive_segment_types: False
  ld_legacy_generation: True

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: ovr1
    type: code
    start: 0x0
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x0, c, autogen/ovr1]
      - [0x1704, c, autogen/ovr1/func_80011704]
      - [0x17C4, c, autogen/ovr1_0]
      - [0x2274, c, autogen/ovr1/func_80012274]
      - [0x22C4, c, autogen/ovr1_1]
      - [0x5FF8, c, autogen/ovr1/func_80015FF8]
      - [0x6270, c, autogen/ovr1_2]
      - [0x6328, c, autogen/ovr1/func_80016328]
      - [0x6368, c, autogen/ovr1/func_80016368]
      - [0x63B4, c, autogen/ovr1_3]
      - [0x7048, c, autogen/ovr1/func_80017048]
      - [0x7098, c, autogen/ovr1_4]
      - [0x7200, c, autogen/ovr1/func_80017200]
      - [0x7438, c, autogen/ovr1_5]
      - [0x7500, c, autogen/ovr1/func_80017500]
      - [0x7784, c, autogen/ovr1/func_80017784]
      - [0x7964, c, autogen/ovr1_6]
      - [0x7D1C, c, autogen/ovr1/func_80017D1C]
      - [0x7DC8, c, autogen/ovr1/func_80017DC8]
      - [0x7E18, c, autogen/ovr1_7]
      - [0x96BC, c, autogen/ovr1/func_800196BC]
      - [0x9B58, c, autogen/ovr1_8]
      - [0x17C70, c, autogen/ovr1/func_80027C70]
      - [0x17FC4, c, autogen/ovr1_9]
      - [0x199D8, c, autogen/ovr1/func_800299D8]
      - [0x19B60, c, autogen/ovr1_10]
      - [0x1A700, c, autogen/ovr1/func_8002A700]
      - [0x1AAF0, c, autogen/ovr1_11]
      - [0x1B170, c, autogen/ovr1/func_8002B170]
      - [0x1BCF0, c, autogen/ovr1_12]
      - [0x1C76C, c, autogen/ovr1/func_8002C76C]
      - [0x1D058, c, autogen/ovr1_13]
      - [0x1D20C, c, autogen/ovr1/func_8002D20C]
      - [0x1D308, c, autogen/ovr1/func_8002D308]
      - [0x1D664, c, autogen/ovr1_14]
      - [0x1E204, c, autogen/ovr1/func_8002E204]
      - [0x1E390, c, autogen/ovr1_15]
      - [0x1EE98, .rodata, autogen/ovr1/func_80011704]
      - [0x1EEC0, rodata, autogen/ovr1_000]
      - [0x1EF08, .rodata, autogen/ovr1/func_80012274]
      - [0x1EF20, .rodata, autogen/ovr1/func_80015FF8]
      - [0x1EF58, rodata, autogen/ovr1_001]
      - [0x1EFE0, .rodata, autogen/ovr1/func_80016328]
      - [0x1EFF0, .rodata, autogen/ovr1/func_80016368]
      - [0x1F000, rodata, autogen/ovr1_002]
      - [0x1F040, .rodata, autogen/ovr1/func_80017048]
      - [0x1F058, .rodata, autogen/ovr1/func_80017200]
      - [0x1F088, .rodata, autogen/ovr1/func_80017500]
      - [0x1F0B8, .rodata, autogen/ovr1/func_80017784]
      - [0x1F0E0, .rodata, autogen/ovr1/func_80017D1C]
      - [0x1F110, rodata, autogen/ovr1_003]
      - [0x1F150, .rodata, autogen/ovr1/func_80017DC8]
      - [0x1F168, .rodata, autogen/ovr1/func_800196BC]
      - [0x1F1A8, rodata, autogen/ovr1_004]
      - [0x1F1C4, .rodata, autogen/ovr1/func_80027C70]
      - [0x1F1FC, rodata, autogen/ovr1_005]
      - [0x1F20C, .rodata, autogen/ovr1/func_800299D8]
      - [0x1F218, .rodata, autogen/ovr1/func_8002A700]
      - [0x1F248, .rodata, autogen/ovr1/func_8002B170]
      - [0x1F278, .rodata, autogen/ovr1/func_8002C76C]
      - [0x1F2E8, .rodata, autogen/ovr1/func_8002D20C]
      - [0x1F2F0, .rodata, autogen/ovr1/func_8002D308]
      - [0x1F318, rodata, autogen/ovr1_006]
      - [0x1F320, .rodata, autogen/ovr1/func_8002E204]
      - [0x1F350, rodata, autogen/ovr1_007]
  - name: ovr1_sec0
    type: code
    start: 0x1F92C
    vram: 0x8002F92C
    align: 4
    subsegments:
      - [0x1F92C, c, autogen/ovr1_16]
      - [0x1FB18, c, autogen/ovr1/func_8002FB18]
      - [0x20308, c, autogen/ovr1_17]
      - [0x20D18, c, autogen/ovr1/func_80030D18]
      - [0x20D64, c, autogen/ovr1_18]
      - [0x20F94, c, autogen/ovr1/func_80030F94]
      - [0x212FC, c, autogen/ovr1_19]
      - [0x247C4, c, autogen/ovr1/func_800347C4]
      - [0x250FC, c, autogen/ovr1_20]
      - [0x26980, c, autogen/ovr1/func_80036980]
      - [0x26ACC, c, autogen/ovr1_21]
      - [0x27834, c, autogen/ovr1/func_80037834]
      - [0x28540, c, autogen/ovr1_22]
      - [0x2932C, c, autogen/ovr1/func_8003932C]
      - [0x2941C, c, autogen/ovr1_23]
      - [0x2C12C, c, autogen/ovr1/func_8003C12C]
      - [0x2C200, c, autogen/ovr1_24]
      - [0x318E8, c, autogen/ovr1/func_800418E8]
      - [0x319E8, c, autogen/ovr1_25]
      - [0x349C8, c, autogen/ovr1/func_800449C8]
      - [0x34EA4, c, autogen/ovr1_26]
      - [0x35AE8, c, autogen/ovr1/func_80045AE8]
      - [0x365E0, c, autogen/ovr1/func_800465E0]
      - [0x36B58, rodata, autogen/ovr1_008]
      - [0x36BAC, .rodata, autogen/ovr1/func_80030D18]
      - [0x36BC4, .rodata, autogen/ovr1/func_80030F94]
      - [0x36BE0, rodata, autogen/ovr1_009]
      - [0x36BE4, .rodata, autogen/ovr1/func_800347C4]
      - [0x36C04, .rodata, autogen/ovr1/func_80036980]
      - [0x36C24, .rodata, autogen/ovr1/func_80037834]
      - [0x36C3C, .rodata, autogen/ovr1/func_8003932C]
      - [0x36C5C, .rodata, autogen/ovr1/func_8003C12C]
      - [0x36C94, rodata, autogen/ovr1_010]
      - [0x36C9C, rodata, autogen/ovr1_011]
      - [0x36CA4, .rodata, autogen/ovr1/func_800418E8]
      - [0x36CDC, .rodata, autogen/ovr1/func_800449C8]
      - [0x36CFC, .rodata, autogen/ovr1/func_80045AE8]
      - [0x36D5C, .rodata, autogen/ovr1/func_800465E0]
      - [0x36D7C, rodata, autogen/ovr1_012]
      - [0x36DA4, .rodata, autogen/ovr1/func_8002FB18]
      - [0x36DB0, rodata, autogen/ovr1_013]
  - name: ovr1_sec1
    type: code
    start: 0x36FB0
    vram: 0x80046FB0
    align: 4
    subsegments:
      - [0x36FB0, c, autogen/ovr1_27]
      - [0x374F4, c, autogen/ovr1/func_800474F4]
      - [0x377C4, c, autogen/ovr1_28]
      - [0x37EA0, c, autogen/ovr1/func_80047EA0]
      - [0x38140, c, autogen/ovr1_29]
      - [0x38208, c, autogen/ovr1/func_80048208]
      - [0x38258, c, autogen/ovr1/func_80048258]
      - [0x382A8, c, autogen/ovr1_30]
      - [0x39A14, c, autogen/ovr1/func_80049A14]
      - [0x39C68, c, autogen/ovr1_31]
      - [0x3BA40, c, autogen/ovr1/func_8004BA40]
      - [0x3BD1C, c, autogen/ovr1_32]
      - [0x3C1EC, c, autogen/ovr1/func_8004C1EC]
      - [0x3C5C8, c, autogen/ovr1_33]
      - [0x3D474, c, autogen/ovr1/func_8004D474]
      - [0x3D6E4, c, autogen/ovr1_34]
      - [0x3F8B4, c, autogen/ovr1/func_8004F8B4]
      - [0x3FB30, c, autogen/ovr1_35]
      - [0x41BF4, c, autogen/ovr1/func_80051BF4]
      - [0x41F54, c, autogen/ovr1_36]
      - [0x42638, c, autogen/ovr1/func_80052638]
      - [0x42838, c, autogen/ovr1_37]
      - [0x42D84, c, autogen/ovr1/func_80052D84]
      - [0x434B4, c, autogen/ovr1_38]
      - [0x4480C, c, autogen/ovr1/func_8005480C]
      - [0x44B9C, c, autogen/ovr1/func_80054B9C]
      - [0x44CC8, c, autogen/ovr1_39]
      - [0x451BC, c, autogen/ovr1/func_800551BC]
      - [0x45328, c, autogen/ovr1/func_80055328]
      - [0x45808, c, autogen/ovr1_40]
      - [0x45D50, c, autogen/ovr1/func_80055D50]
      - [0x45E90, c, autogen/ovr1_41]
      - [0x46194, c, autogen/ovr1/func_80056194]
      - [0x46810, c, autogen/ovr1_42]
      - [0x4731C, c, autogen/ovr1/func_8005731C]
      - [0x47450, c, autogen/ovr1_43]
      - [0x474C0, c, autogen/ovr1/func_800574C0]
      - [0x475F8, c, autogen/ovr1_44]
      - [0x47A70, c, autogen/ovr1/func_80057A70]
      - [0x47D24, c, autogen/ovr1_45]
      - [0x485C0, c, autogen/ovr1/func_800585C0]
      - [0x487BC, c, autogen/ovr1_46]
      - [0x48E28, c, autogen/ovr1/func_80058E28]
      - [0x4916C, c, autogen/ovr1_47]
      - [0x49800, c, autogen/ovr1/func_80059800]
      - [0x49A7C, c, autogen/ovr1_48]
      - [0x4A5F8, c, autogen/ovr1/func_8005A5F8]
      - [0x4A77C, .rodata, autogen/ovr1/func_800474F4]
      - [0x4A79C, .rodata, autogen/ovr1/func_80047EA0]
      - [0x4A7B4, rodata, autogen/ovr1_014]
      - [0x4A840, .rodata, autogen/ovr1/func_80048208]
      - [0x4A854, .rodata, autogen/ovr1/func_80048258]
      - [0x4A860, rodata, autogen/ovr1_015]
      - [0x4A868, .rodata, autogen/ovr1/func_80049A14]
      - [0x4A898, .rodata, autogen/ovr1/func_8004BA40]
      - [0x4A8C0, .rodata, autogen/ovr1/func_8004C1EC]
      - [0x4A8D8, rodata, autogen/ovr1_016]
      - [0x4A928, .rodata, autogen/ovr1/func_8004D474]
      - [0x4A94C, rodata, autogen/ovr1_017]
      - [0x4A97C, rodata, autogen/ovr1_018]
      - [0x4A984, .rodata, autogen/ovr1/func_80052D84]
      - [0x4A9A8, rodata, autogen/ovr1_019]
      - [0x4A9B0, .rodata, autogen/ovr1/func_80054B9C]
      - [0x4A9E0, rodata, autogen/ovr1_020]
      - [0x4A9E4, .rodata, autogen/ovr1/func_800551BC]
      - [0x4AA44, .rodata, autogen/ovr1/func_80055328]
      - [0x4AAA4, .rodata, autogen/ovr1/func_80055D50]
      - [0x4AACC, .rodata, autogen/ovr1/func_80056194]
      - [0x4AAE4, .rodata, autogen/ovr1/func_8005731C]
      - [0x4AB04, .rodata, autogen/ovr1/func_800574C0]
      - [0x4AB24, .rodata, autogen/ovr1/func_80057A70]
      - [0x4AB48, rodata, autogen/ovr1_021]
      - [0x4AB50, .rodata, autogen/ovr1/func_80059800]
      - [0x4AB58, rodata, autogen/ovr1_022]
      - [0x4B1E4, rodata, autogen/ovr1_023]
      - [0x4B1E8, rodata, autogen/ovr1_024]
      - [0x4B664, .rodata, autogen/ovr1/func_80051BF4]
      - [0x4B668, rodata, autogen/ovr1_025]
      - [0x4B68C, .rodata, autogen/ovr1/func_80052638]
      - [0x4B690, rodata, autogen/ovr1_026]
      - [0x4C488, rodata, autogen/ovr1_027]
      - [0x4C4A4, rodata, autogen/ovr1_028]
      - [0x4D334, .rodata, autogen/ovr1/func_800585C0]
      - [0x4D338, rodata, autogen/ovr1_029]
      - [0x4D344, rodata, autogen/ovr1_030]
      - [0x4D348, rodata, autogen/ovr1_031]
      - [0x4D5AC, .rodata, autogen/ovr1/func_8005A5F8]
      - [0x4D5B0, rodata, autogen/ovr1_032]
  - [0x4D5F8]
