name: gt2_01
sha1: b8e5d9ea443c41ad7206882a4b8deb579c769948
options:
  basename: gt2_01
  target_path: ovl_bin/gt2_01.exe
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  create_asm_dependencies: True

  ld_script_path: autogen/gt2_01.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - ovr1_symbol_addrs.txt
  reloc_addrs_path:
    - ovr1_reloc_addrs.txt

  undefined_funcs_auto_path: autogen/ovr1_undefined_funcs_auto.txt
  undefined_syms_auto_path: autogen/ovr1_undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: ovr1
    type: code
    start: 0x0
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x0, c, autogen/ovr1]
  - [0x4D5F8]
