name: gt2_05
sha1: 76d3d705ad6e452030f98d15a4a8a3b0f5bdc280
options:
  basename: gt2_05
  target_path: ovl_bin/gt2_05.exe
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  create_asm_dependencies: True

  ld_script_path: autogen/gt2_05.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  #asm_inc_header: ".include \"include/macro.inc\"\n\n"
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".text", ".rodata", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - ovr5_symbol_addrs.txt
  reloc_addrs_path:
    - ovr5_reloc_addrs.txt

  undefined_funcs_auto_path: autogen/ovr5_undefined_funcs_auto.txt
  create_undefined_syms_auto: False

  pair_rodata_to_text: True
  migrate_rodata_to_functions: True

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: ovr5
    type: code
    start: 0x0
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x0, c, autogen/ovr5]
      - [0x3108, c, autogen/ovr5/func_80013108]
      - [0x3628, c, autogen/ovr5_0]
      - [0x4380, c, autogen/ovr5/func_80014380]
      - [0x4E60, c, autogen/ovr5_1]
      - [0x4FEC, c, autogen/ovr5/func_80014FEC]
      - [0x503C, c, autogen/ovr5/func_8001503C]
      - [0x5088, c, autogen/ovr5_2]
      - [0x53B4, c, autogen/ovr5/func_800153B4]
      - [0x5404, c, autogen/ovr5_3]
      - [0x706C, c, autogen/ovr5/func_8001706C]
      - [0x719C, c, autogen/ovr5_4]
      - [0x83EC, c, autogen/ovr5/gt2_ovr5_is_international_league]
      - [0x847C, c, autogen/ovr5_5]
      - [0x859C, c, autogen/ovr5/gt2_ovr5_is_gt_world_cup]
      - [0x8608, c, autogen/ovr5_6]
      - [0x861C, c, autogen/ovr5/gt2_ovr5_get_machine_test_game_mode]
      - [0x8690, c, autogen/ovr5/gt2_ovr5_is_event_synthesizer]
      - [0x8768, c, autogen/ovr5/func_80018768]
      - [0x87DC, c, autogen/ovr5_7]
      - [0x8A84, c, autogen/ovr5/func_80018A84]
      - [0x8BF4, c, autogen/ovr5_8]
      - [0x9364, c, autogen/ovr5/func_80019634]
      - [0x96C4, c, autogen/ovr5_9]
      - [0x973C, c, autogen/ovr5/func_8001973C]
      - [0x9B84, c, autogen/ovr5_10]
      - [0xB6F0, c, autogen/ovr5/func_8001B6F0]
      - [0xB818, c, autogen/ovr5_11]
      - [0xB9AC, c, autogen/ovr5/gt2_ovr5_get_stat_widget_display_value]
      - [0xD0B0, c, autogen/ovr5_12]
      - [0xD0E8, c, autogen/ovr5_13]
      - [0xDCD0, c, autogen/ovr5/func_8001DCD0]
      - [0xDD3C, c, autogen/ovr5/func_8001DD3C]
      - [0xDDAC, c, autogen/ovr5/func_8001DDAC]
      - [0xDFEC, c, autogen/ovr5/gt2_ovr5_ui_can_buy_caller0]
      - [0xE22C, c, autogen/ovr5_14]
      - [0xE26C, c, autogen/ovr5/func_8001E26C]
      - [0xE328, c, autogen/ovr5_15]
      - [0x10110, c, autogen/ovr5/gt2_ovr5_format_number]
      - [0x10198, c, autogen/ovr5_16]
      - [0x12964, rodata, autogen/ovr5_00]
      - [0x129AC, .rodata, autogen/ovr5/func_80013108]
      - [0x129B4, .rodata, autogen/ovr5/func_80014380]
      - [0x12C5C, rodata, autogen/ovr5_01]
      - [0x12CE8, .rodata, autogen/ovr5/func_80014FEC]
      - [0x12CF8, .rodata, autogen/ovr5/func_8001503C]
      - [0x12D00, rodata, autogen/ovr5_02]
      - [0x12D48, .rodata, autogen/ovr5/func_800153B4]
      - [0x12D58, rodata, autogen/ovr5_03]
      - [0x12D5C, .rodata, autogen/ovr5/func_8001706C]
      - [0x12E24, rodata, autogen/ovr5_04]
      - [0x12E64, .rodata, autogen/ovr5/gt2_ovr5_is_international_league]
      - [0x12F1C, .rodata, autogen/ovr5/gt2_ovr5_is_gt_world_cup]
      - [0x12F20, .rodata, autogen/ovr5/gt2_ovr5_get_machine_test_game_mode]
      - [0x12F38, .rodata, autogen/ovr5/gt2_ovr5_is_event_synthesizer]
      - [0x12F50, .rodata, autogen/ovr5/func_80018768]
      - [0x12F74, .rodata, autogen/ovr5/func_80018A84]
      - [0x139BC, .rodata, autogen/ovr5/func_80019634]
      - [0x139D4, .rodata, autogen/ovr5/func_8001973C]
      - [0x13A0C, .rodata, autogen/ovr5/func_8001B6F0]
      - [0x13CFC, .rodata, autogen/ovr5/gt2_ovr5_get_stat_widget_display_value]
      - [0x1405C, .rodata, autogen/ovr5/func_8001DCD0]
      - [0x1407C, .rodata, autogen/ovr5/func_8001DD3C]
      - [0x14094, .rodata, autogen/ovr5/func_8001DDAC]
      - [0x141CC, .rodata, autogen/ovr5/gt2_ovr5_ui_can_buy_caller0]
      - [0x14284, .rodata, autogen/ovr5/func_8001E26C]
      - [0x142A4, .rodata, autogen/ovr5/gt2_ovr5_format_number]
      - [0x142A8, rodata, autogen/ovr5_05]
      - [0x14430, data, autogen/ovr5]
  - [0x42A74]
