name: SCUS_944.88
sha1: 3030aa271c0a4022fc69ce09d76a6bc75e69a32a
options:
  basename: scus_944.88
  target_path: orig_bin/SCUS_944.88
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  asset_path: ../../assets
  create_asm_dependencies: True

  ld_script_path: autogen/scus_944.88.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - mainexe_symbol_addrs.txt
  reloc_addrs_path:
    - mainexe_reloc_addrs_exe.txt

  undefined_funcs_auto_path: autogen/mainexe_undefined_funcs_auto.txt
  create_undefined_syms_auto: False
  #undefined_syms_auto_path: autogen/mainexe_undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: ovr0
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, asm, ovr0/gt2_main_task0a_ovr_func0]
      - [0x8C0, c, ovr0/gt2_main_task0a_ovr_entrypoint]
      - [0x8E4, c, autogen/ovr0]
      - [0x1614, c, ovr0/gt2_main_task0]
      - [0x16CC, c, ovr0/gt2_show_vendor_bootlogo_task0]
      - [0x171C, c, autogen/ovr0_1]
      - [0x1C6C, c, ovr0/gt2_main_task0a_ovr_func1]
      - [0x1C94, c, autogen/ovr0_2]

  - name: data
    type: data
    start: 0x2530
    vram: 0x80011D30
    align: 4
    subsegments:
      - [0x2530, data, rodata-pt1]
  
  - name: textures
    type: bin
    start: 0x25F8
    vram: 0x80011DF8
    align: 4
    subsegments:
      - [0x25F8, bin, notice.tim.gz]
      - [0x23A2C, bin, logo-scea.tim.gz]

  - name: data2
    type: data
    start: 0x245A0
    vram: 0x80033DA0
    align: 4
    subsegments:
      - [0x245A0, data, rodata-pt2]

  - name: bootstrap
    type: code
    start: 0x4DE00
    vram: 0x8005D600
    align: 4
    subsegments:
      - [0x4DE00, c, autogen/start]
  - [0x99800]
