name: SCUS_944.88
sha1: 3030aa271c0a4022fc69ce09d76a6bc75e69a32a
options:
  basename: scus_944.88
  target_path: orig_bin/SCUS_944.88
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  asset_path: ../../assets
  create_asm_dependencies: True

  ld_script_path: autogen/scus_944.88.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - mainexe_symbol_addrs.txt
  reloc_addrs_path:
    - mainexe_reloc_addrs_exe.txt

  undefined_funcs_auto_path: autogen/mainexe_undefined_funcs_auto.txt
  create_undefined_syms_auto: False
  #undefined_syms_auto_path: autogen/mainexe_undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: ovr0
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, c, autogen/ovr0]
      - [0x8C0, c, ovr0/gt2_main_task0a_ovr_entrypoint]
      - [0x8E4, c, ovr0/gt2_ovr0_vol_search_vol_dir]
      - [0x9FC, c, ovr0/gt2_unknown_task0]
      - [0xA28, c, autogen/ovr0_1]
      - [0xC7C, c, ovr0/gt2_main_task0b7]
      - [0xCA0, c, autogen/ovr0_2]
      - [0xF98, c, ovr0/gt2_main_task0b30]
      - [0xFB4, c, ovr0/gt2_main_task0b34]
      - [0xFE8, c, ovr0/gt2_main_task0b4]
      - [0x102C, c, ovr0/gt2_main_task0b5]
      - [0x103C, c, ovr0/gt2_main_task0b6]
      - [0x1068, c, ovr0/gt2_main_task0b]
      - [0x10C0, c, autogen/ovr0_3]
      - [0x1128, c, ovr0/gt2_vsync_handler]
      - [0x1154, c, ovr0/gt2_sysinit_vsync_setup]
      - [0x1198, c, ovr0/gt2_sysinit]
      - [0x1224, c, autogen/ovr0_5]
      - [0x1260, c, ovr0/gt2_main_task078]
      - [0x1288, c, autogen/ovr0_6]
      - [0x12D4, c, ovr0/gt2_unknown_task1]
      - [0x12F0, c, autogen/ovr0_7]
      - [0x1614, c, ovr0/gt2_main_task0]
      - [0x16CC, c, ovr0/gt2_show_vendor_bootlogo_task0]
      - [0x171C, c, ovr0/gt2_main_task0800]
      - [0x175C, c, autogen/ovr0_8]
      - [0x1C6C, c, ovr0/gt2_main_task0a_ovr_func1]
      - [0x1C94, c, autogen/ovr0_9]
      - [0x1F08, c, ovr0/gt2_main_task0b01_noop_loader]
      - [0x1F10, c, autogen/ovr0_A]
      - [0x22F4, c, ovr0/gt2_main_task0b0_car_loader]
      - [0x233C, c, autogen/ovr0_B]
      - [0x24E4, c, ovr0/gt2_main_task0b2]

  - name: data
    type: data
    start: 0x2530
    vram: 0x80011D30
    align: 4
    subsegments:
      - [0x2530, data, rodata-pt1]
  
  - name: textures
    type: bin
    start: 0x25F8
    vram: 0x80011DF8
    align: 4
    subsegments:
      - [0x25F8, bin, notice.tim.gz]
      - [0x23A2C, bin, logo-scea.tim.gz]

  - name: data2
    type: data
    start: 0x245A0
    vram: 0x80033DA0
    align: 4
    subsegments:
      - [0x245A0, data, rodata-pt2]

  - name: bootstrap
    type: code
    start: 0x4DE00
    vram: 0x8005D600
    align: 4
    subsegments:
      - [0x4DE00, c, autogen/start]
      - [0x4DEE0, c, start/gt2_main]
      - [0x4DF18, c, start/gt2_main_shared_arcaderace_func32]
      - [0x4DF4C, c, autogen/start_0]
      - [0x4DF68, c, start/gt2_main_shared_arcaderace_func33]
      - [0x4DF9C, c, autogen/start_1]
      - [0x4E0D4, c, start/gt2_main_shared_gtracemenu_func0]
      - [0x4E108, c, start/gt2_main_task0b110]
      - [0x4E12C, c, autogen/start_2]
      - [0x4E390, c, start/gt2_main_shared_gt_race_func1]
      - [0x4E3C0, c, autogen/start_3]
      - [0x4E464, c, start/gt2_main_race_func1]
      - [0x4E49C, c, autogen/start_4]
      - [0x4FF88, c, start/gt2_unknown_nop0]
      - [0x4FF90, c, autogen/start_5]
      - [0x73C9C, c, start/gt2_unknown_nop1]
      - [0x73CA4, c, start/gt2_unknown_nop2]
      - [0x73CAC, c, start/gt2_unknown_nop3]  
      - [0x73CB4, c, start/gt2_unknown_nop4]
      - [0x73CBC, c, autogen/start_6]     
      - [0x76174, c, start/gt2_exit]
      - [0x76190, c, start/gt2_exit_task0]
      - [0x761FC, c, autogen/start_7]
  - [0x99800]
