name: SCUS_944.88
sha1: 3030aa271c0a4022fc69ce09d76a6bc75e69a32a
options:
  basename: scus_944.88
  target_path: orig_bin/SCUS_944.88
  base_path: .
  platform: psx
  compiler: GCC

  asm_path: ../../asm
  src_path: ../../src
  build_path: ../../build
  asset_path: ../../assets
  create_asm_dependencies: True

  ld_script_path: autogen/scus_944.88.ld

  find_file_boundaries: False
  gp_value: 0x00000000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".text", ".rodata", ".data", ".bss"]
  # auto_all_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - mainexe_symbol_addrs.txt
  reloc_addrs_path:
    - mainexe_reloc_addrs_exe.txt

  undefined_funcs_auto_path: autogen/mainexe_undefined_funcs_auto.txt
  create_undefined_syms_auto: False
  #undefined_syms_auto_path: autogen/mainexe_undefined_syms_auto.txt

  migrate_rodata_to_functions: True

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: ovr0
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, c, autogen/ovr0/gt2_ovr0_task0a_ovr_func0]
      - [0x8C0, c, ovr0/gt2_ovr0_task0a_ovr_entrypoint]
      - [0x8E4, c, ovr0/gt2_ovr0_vol_search_vol_dir]
      - [0x9FC, c, ovr0/gt2_unknown_task0]
      - [0xA28, c, ovr0/gt2_ovr0_vol_build_file_indices_cache]
      - [0xADC, c, ovr0/gt2_ovr0_vol_gtfs_init]
      - [0xC7C, c, ovr0/gt2_main_task0b7]
      - [0xCA0, c, autogen/ovr0]
      - [0xF98, c, ovr0/gt2_main_task0b30]
      - [0xFB4, c, ovr0/gt2_main_task0b34]
      - [0xFE8, c, ovr0/gt2_main_task0b4]
      - [0x102C, c, ovr0/gt2_main_task0b5]
      - [0x103C, c, ovr0/gt2_main_task0b6]
      - [0x1068, c, ovr0/gt2_ovr0_task0b]
      - [0x10C0, c, autogen/ovr0_0]
      - [0x1128, c, ovr0/gt2_vsync_handler]
      - [0x1154, c, ovr0/gt2_sysinit_vsync_setup]
      - [0x1198, c, ovr0/gt2_sysinit]
      - [0x1224, c, autogen/ovr0_1]
      - [0x1260, c, ovr0/gt2_main_task078]
      - [0x1288, c, ovr0/gt2_main_task075]
      - [0x12D4, c, ovr0/gt2_unknown_task1]
      - [0x12F0, c, autogen/ovr0_2]
      - [0x1614, c, ovr0/gt2_ovr0_task0]
      - [0x16CC, c, ovr0/gt2_show_vendor_bootlogo_task0]
      - [0x171C, c, ovr0/gt2_main_task0800]
      - [0x175C, c, autogen/ovr0/gt2_ovr0_task080]
      - [0x1954, c, autogen/ovr0_3]
      - [0x1A4C, c, autogen/ovr0/gt2_ovr0_vol_loader_task3]
      - [0x1C6C, c, ovr0/gt2_main_task0a_ovr_func1]
      - [0x1C94, c, autogen/ovr0/gt2_ovr0_task08_play_music_a440]
      - [0x1D70, c, autogen/ovr0_4]
      - [0x1F08, c, ovr0/gt2_main_task0b01_noop_loader]
      - [0x1F10, c, autogen/ovr0/gt2_ovr0_task0b02_carobj_loader]
      - [0x2020, c, autogen/ovr0/gt2_ovr0_task0b03_carlogo_loader]
      - [0x214C, c, autogen/ovr0/gt2_ovr0_task0b04_carwheel_loader]
      - [0x2210, c, autogen/ovr0/gt2_ovr0_task0b05_enginedata_loader]
      - [0x22F4, c, ovr0/gt2_ovr0_task0b0_car_loader]
      - [0x233C, c, ovr0/gt2_ovr0_strchr]
      - [0x2370, c, autogen/ovr0/gt2_ovr0_task0b10]
      - [0x2470, c, autogen/ovr0_5]
      - [0x24E4, c, ovr0/gt2_main_task0b2]
      - [0x2530, .rodata, autogen/ovr0/gt2_ovr0_task0a_ovr_func0]
      - [0x2538, .rodata, ovr0/gt2_ovr0_task0]
      - [0x253C, rodata, ovr0_0]
      - [0x2584, .rodata, ovr0/gt2_show_vendor_bootlogo_task0]
      - [0x2598, .rodata, autogen/ovr0/gt2_ovr0_task080]
      - [0x25A0, .rodata, autogen/ovr0/gt2_ovr0_vol_loader_task3]
      - [0x25A4, .rodata, autogen/ovr0/gt2_ovr0_task08_play_music_a440]
      - [0x25C4, .rodata, autogen/ovr0/gt2_ovr0_task0b02_carobj_loader]
      - [0x25CC, .rodata, autogen/ovr0/gt2_ovr0_task0b03_carlogo_loader]
      - [0x25D8, .rodata, autogen/ovr0/gt2_ovr0_task0b04_carwheel_loader]
      - [0x25E4, .rodata, autogen/ovr0/gt2_ovr0_task0b05_enginedata_loader]
      - [0x25EC, .rodata, autogen/ovr0/gt2_ovr0_task0b10]
      - [0x25F4, rodata, ovr0_1]
      - [0x25F8, bin, notice.tim.gz]
      - [0x23A2C, bin, logo-scea.tim.gz]
      - [0x245A0, data, ovr0_data]
      - [0x245F0, .bss, ovr0/gt2_ovr0_vol_build_file_indices_cache]

  - name: ovr0_padding
    type: bss
    start: 0x247F0
    vram: 0x80033FF0
    align: 4

  - name: gt2main
    type: code
    start: 0x4DE00
    vram: 0x8005D600
    align: 4
    subsegments:
      - [0x4DE00, c, autogen/start]
      - [0x4DEE0, c, start/gt2_main]
      - [0x4DF18, c, start/gt2_main_shared_arcaderace_func32]
      - [0x4DF4C, c, start/gt2_main_vol_get_file_data_sector_offset]
      - [0x4DF68, c, start/gt2_main_shared_arcaderace_func33]
      - [0x4DF9C, c, autogen/start_0]
      - [0x4E0A0, c, start/gt2_main_task0b11]
      - [0x4E0D4, c, start/gt2_main_shared_gtracemenu_func0]
      - [0x4E108, c, start/gt2_main_task0b110]
      - [0x4E12C, c, start/gt2_main_shared_racegtarcade_func6]
      - [0x4E150, c, autogen/start_1]
      - [0x4E1BC, c, start/gt2_sysinit_task0]
      - [0x4E1F0, c, start/gt2_main_task1]
      - [0x4E23C, c, start/gt2_main_task2]
      - [0x4E27C, c, autogen/start_2]
      - [0x4E390, c, start/gt2_main_shared_gt_race_get_completion_flag]
      - [0x4E3C0, c, autogen/start_3]
      - [0x4E464, c, start/gt2_main_race_func1]
      - [0x4E49C, c, start/gt2_main_race_func2]
      - [0x4E4F4, c, autogen/start_4]
      - [0x4E568, c, start/gt2_main_task0b31]
      - [0x4E594, c, autogen/start_5]
      - [0x4E83C, c, start/gt2_main_race_func4]
      - [0x4E87C, c, autogen/start_6]
      - [0x4EE24, c, start/gt2_main_race_func7]
      - [0x4EE58, c, start/gt2_memset_caller_ovr5]
      - [0x4EE7C, c, start/gt2_main_race_func8]
      - [0x4EEB0, c, autogen/start_7]
      - [0x4EF3C, c, start/gt2_memset_caller_15a5c]
      - [0x4EF64, c, autogen/start_8]
      - [0x4F2A4, c, start/gt2_main_race_switch_func12]
      - [0x4F2C0, c, autogen/start/gt2_main_shared_gt_race_func3]
      - [0x4F64C, c, start/gt2_main_race_switch_func0]
      - [0x4F844, c, autogen/start/gt2_main_shared_gt_race_func5]
      - [0x4FC10, c, autogen/start_9]
      - [0x4FF88, c, start/gt2_unknown_nop0]
      - [0x4FF90, c, autogen/start_10]
      - [0x50000, c, start/gt2_main_race_switch_func13]
      - [0x50014, c, start/gt2_main_race_setter5]
      - [0x50020, c, start/gt2_main_race_setter0]
      - [0x50034, c, autogen/start_11]
      - [0x500F0, c, start/gt2_main_race_setter1]
      - [0x50104, c, start/gt2_main_race_setter2]
      - [0x50118, c, start/gt2_main_race_setter3]
      - [0x5012C, c, autogen/start_12]
      - [0x501DC, c, autogen/start/gt2_main_race_switch_func2]
      - [0x5049C, c, autogen/start/gt2_main_shared_race_func0]
      - [0x50C10, c, autogen/start/gt2_main_race_switch_func1]
      - [0x51040, c, autogen/start_13]
      - [0x51810, c, start/gt2_main_shared_race_func2_nop]
      - [0x5181C, c, autogen/start_14]
      - [0x51B08, c, autogen/start/gt2_main_shared_arcadegtrace_func0]
      - [0x51C90, c, autogen/start_15]
      - [0x594A0, c, autogen/start/gt2_main_race_maxspeed_format]
      - [0x59508, c, autogen/start_16]
      - [0x5A118, c, start/gt2_main_race_func16_001]
      - [0x5A12C, c, autogen/start_17]
      - [0x5A7F8, c, start/gt2_main_shared_racemenu_func3010]
      - [0x5A800, c, autogen/start_18]
      - [0x5AAE4, c, start/gt2_main_shared_menuarcade_func3]
      - [0x5AAEC, c, start/gt2_main_menu_func3]
      - [0x5AAF4, c, start/gt2_main_menu_func4]
      - [0x5AAFC, c, start/gt2_main_menu_func5]
      - [0x5AB04, c, start/gt2_main_menu_func6]
      - [0x5AB0C, c, start/gt2_main_menu_func7]
      - [0x5AB14, c, autogen/start_19]
      - [0x5ABFC, c, autogen/start/gt2_main_race_func16_1418]
      - [0x5ACE4, c, autogen/start/gt2_main_race_func16_141]
      - [0x5B268, c, autogen/start/gt2_main_func53]
      - [0x5B468, c, autogen/start_20]
      - [0x5C6B4, c, autogen/start/gt2_main_shared_racemenu_func40]
      - [0x5C6F4, c, autogen/start_21]
      - [0x5E2F8, c, autogen/start/gt2_main_shared_racemenu_func43]
      - [0x5E4B8, c, autogen/start/gt2_main_shared_arcaderace_funcE]
      - [0x5E5D0, c, start/gt2_main_shared_arcaderace_funcF]
      - [0x5E60C, c, start/gt2_unknown_task4]
      - [0x5E61C, c, autogen/start_22]
      - [0x5F364, c, autogen/start/gt2_main_shared_racemenuarcade_funcE]
      - [0x5F3F0, c, autogen/start_23]
      - [0x62330, c, autogen/start/gt2_main_funcA]
      - [0x62654, c, autogen/start_24]
      - [0x62C8C, c, start/gt2_main_race_func16_20]
      - [0x62C94, c, autogen/start_25]
      - [0x630F0, c, autogen/start/gt2_main_shared_racemenu_func5]
      - [0x63378, c, autogen/start_26]
      - [0x6378C, c, start/gt2_main_race_func20]
      - [0x6379C, c, autogen/start_27]
      - [0x644E4, c, start/gt2_main_race_func21]
      - [0x644FC, c, autogen/start_28]
      - [0x64530, c, start/gt2_main_race_func23]
      - [0x6454C, c, autogen/start_29]
      - [0x66870, c, autogen/start/gt2_main_switch_func000]
      - [0x66A40, c, autogen/start/gt2_main_shared_gt_race_func31]
      - [0x66B00, c, autogen/start/gt2_main_shared_gt_race_func50]
      - [0x66BC0, c, autogen/start_30]
      - [0x66D70, c, autogen/start/gt2_main_gtmode_get_part_number]
      - [0x66F48, c, autogen/start_31]
      - [0x67574, c, autogen/start/gt2_main_menu_func1]
      - [0x67604, c, autogen/start/gt2_main_shared_menuarcade_func1]
      - [0x67688, c, autogen/start/gt2_main_shared_racemenu_func7]
      - [0x6770C, c, autogen/start_32]
      - [0x67A14, c, autogen/start/gt2_main_shared_gt_race_func0]
      - [0x67E34, c, autogen/start/gt2_main_copyfunc0]
      - [0x68000, c, autogen/start_33]
      - [0x682AC, c, start/gt2_main_shared_gt_race_func02]
      - [0x682C4, c, autogen/start_34]
      - [0x6849C, c, start/gt2_main_shared_gt_race_func05_nop]
      - [0x684A4, c, autogen/start_35]
      - [0x68F90, c, start/gt2_main_task0b20]
      - [0x68FA8, c, autogen/start_36]
      - [0x69F44, c, autogen/start/gt2_main_task02100]
      - [0x6A238, c, autogen/start_37]
      - [0x6B558, c, start/gt2_main_saveregisters]
      - [0x6B590, c, autogen/start_38]
      - [0x6CC2C, c, start/gt2_main_task031_nop_zero]
      - [0x6CC34, c, start/gt2_main_task032_nop]
      - [0x6CC3C, c, autogen/start_39]
      - [0x6CF44, c, autogen/start/gt2_switchtable_user0]
      - [0x6D1E8, c, autogen/start_40]
      - [0x6D2A4, c, autogen/start/gt2_main_task033]
      - [0x6D5F4, c, autogen/start_41]
      - [0x6E280, c, start/gt2_main_race_func16_1411]
      - [0x6E29C, c, autogen/start_42]
      - [0x6F2CC, c, autogen/start/gt2_main_task05_sdkevent_f2]
      - [0x6F81C, c, autogen/start_43]
      - [0x70430, c, autogen/start/gt2_main_task04_pad_config_task01]
      - [0x70634, c, autogen/start_44]
      - [0x70838, c, autogen/start/gt2_callback_double_buffer_flip]
      - [0x70888, c, autogen/start_45]
      - [0x70D1C, c, autogen/start/gt2_main_shared_racemenuarcade_func430]
      - [0x71020, c, autogen/start_46]
      - [0x71494, c, start/gt2_main_sharedovr_func15_nop]
      - [0x7149C, c, start/gt2_main_sharedovr_func_15_ret1]
      - [0x714A4, c, autogen/start_47]
      - [0x71504, c, start/gt2_main_sharedovr_func6_nop]
      - [0x7150C, c, autogen/start_48]
      - [0x7169C, c, autogen/start/gt2_callback_double_buffer_flip_prep]
      - [0x716EC, c, autogen/start_49]
      - [0x7187C, c, start/gt2_main_race_func41_0]
      - [0x71884, c, autogen/start_50]
      - [0x728E0, c, autogen/start/gt2_main_gtmode_task7000_error]
      - [0x7297C, c, autogen/start_51]
      - [0x732E4, c, start/gt2_unknown_task1F]
      - [0x732EC, c, autogen/start_52]
      - [0x73C9C, c, start/gt2_unknown_nop1]
      - [0x73CA4, c, start/gt2_unknown_nop2]
      - [0x73CAC, c, start/gt2_unknown_nop3]  
      - [0x73CB4, c, start/gt2_unknown_nop4]      
      - [0x73CBC, c, autogen/start/gt2_main_invoke_flip_14ScreenViewLoop]
      - [0x73CFC, c, autogen/start_53]
      - [0x73F08, c, start/gt2_unknown_task22]
      - [0x73F1C, c, autogen/start_54]
      - [0x76174, c, start/gt2_exit]
      - [0x76190, c, start/gt2_exit_task0]
      - [0x761FC, c, autogen/start_55]
      - [0x763B0, c, start/gt2_unknown_task24]
      - [0x763C4, c, autogen/start_56]
      - [0x76638, c, autogen/start/gt2_flip_class_type_info]
      - [0x76688, c, autogen/start_57]
      - [0x766D8, c, autogen/start/gt2_flip_si_type_info]
      - [0x76728, c, autogen/start_58]
      - [0x76774, c, autogen/start/gt2_flip_user_type_info]
      - [0x767C4, c, autogen/start_59]
      - [0x767E4, c, start/gt2_main_compare_2neq1]
      - [0x767F0, c, start/gt2_main_compare_2eq1]
      - [0x767FC, c, start/gt2_main_return_arb_ptr0]
      - [0x76808, c, start/gt2_main_set_arb_ptr_from_int0]
      - [0x76820, c, autogen/start/gt2_flip_type_info]
      - [0x76860, c, autogen/start_60]
      - [0x76E58, c, lib/libpress]
      - [0x774E8, c, lib/lib]
      - [0x7D608, c, start/gt2_init]
      - [0x7D630, c, autogen/start_61]
      - [0x7D6DC, c, start/gt2_main_strcpy_slim]
      - [0x7D700, c, autogen/start_62]
      - [0x7D764, c, start/gt2_main_strcpy]
      - [0x7D7C4, c, start/gt2_main_strlen]
      - [0x7D7E0, c, start/gt2_main_task0a_ovr_memcpy]
      - [0x7D820, c, autogen/start_63]
      - [0x7DFA4, c, autogen/start/gt2_unknown_task14_003]
      - [0x7E084, c, autogen/start_64]
      - [0x7E0D4, c, autogen/start/gt2_unknown_task14_00]
      - [0x7E574, c, autogen/start_65]
      - [0x7E7C4, asm, bios/bcopy]
      - [0x7E7D4, asm, bios/strncmp]
      - [0x7E7E4, asm, bios/bzero]
      - [0x7E7F4, asm, bios/printf]
      - [0x7E80C, asm, bios/puts]
      - [0x7E824, rodata, gt2main0]
      - [0x80070, .rodata, autogen/start/gt2_main_shared_gt_race_func3]
      - [0x800D0, .rodata, start/gt2_main_race_switch_func0]
      - [0x80130, .rodata, autogen/start/gt2_main_shared_gt_race_func5]
      - [0x80190, .rodata, autogen/start/gt2_main_race_switch_func2]
      - [0x801D8, .rodata, autogen/start/gt2_main_shared_race_func0]
      - [0x80220, .rodata, autogen/start/gt2_main_race_switch_func1]
      - [0x80268, .rodata, autogen/start/gt2_main_race_maxspeed_format]
      - [0x80270, rodata, gt2main1]
      - [0x80274, .rodata, autogen/start/gt2_main_race_func16_1418]
      - [0x8027C, .rodata, autogen/start/gt2_main_race_func16_141]
      - [0x802AC, .rodata, autogen/start/gt2_main_shared_racemenu_func43]
      - [0x802B0, .rodata, autogen/start/gt2_main_shared_racemenuarcade_funcE]
      - [0x802C8, rodata, gt2main2]
      - [0x802D0, .rodata, autogen/start/gt2_main_funcA]
      - [0x80314, rodata, gt2main3]
      - [0x80320, .rodata, autogen/start/gt2_main_shared_racemenu_func5]
      - [0x80338, rodata, gt2main4]
      - [0x80340, .rodata, autogen/start/gt2_main_switch_func000]
      - [0x80370, .rodata, autogen/start/gt2_main_shared_gt_race_func31]
      - [0x803E0, .rodata, autogen/start/gt2_main_shared_gt_race_func50]
      - [0x80450, .rodata, autogen/start/gt2_main_gtmode_get_part_number]
      - [0x80520, .rodata, autogen/start/gt2_main_shared_gt_race_func0]
      - [0x80558, .rodata, autogen/start/gt2_main_copyfunc0]
      - [0x80598, .rodata, autogen/start/gt2_main_task02100]
      - [0x805B8, rodata, gt2main5]
      - [0x80AB8, .rodata, autogen/start/gt2_switchtable_user0]
      - [0x80AF8, .rodata, autogen/start/gt2_main_task033]
      - [0x80BB4, rodata, gt2main6]
      - [0x80DA0, .rodata, autogen/start/gt2_main_task05_sdkevent_f2]
      - [0x80DF8, .rodata, autogen/start/gt2_main_task04_pad_config_task01]
      - [0x80E30, rodata, gt2main7]
      - [0x80E74, .rodata, autogen/start/gt2_callback_double_buffer_flip]
      - [0x80E90, .rodata, autogen/start/gt2_main_shared_racemenuarcade_func430]
      - [0x80EC8, rodata, gt2main8]
      - [0x80F0C, .rodata, autogen/start/gt2_callback_double_buffer_flip_prep]
      - [0x80F1C, rodata, gt2main9]
      - [0x81094, .rodata, autogen/start/gt2_main_gtmode_task7000_error]
      - [0x810EC, rodata, gt2main10]
      - [0x8110C, .rodata, autogen/start/gt2_main_invoke_flip_14ScreenViewLoop]
      - [0x81120, rodata, gt2main11]
      - [0x8128C, .rodata, autogen/start/gt2_flip_class_type_info]
      - [0x812A0, .rodata, autogen/start/gt2_flip_si_type_info]
      - [0x812B4, .rodata, autogen/start/gt2_flip_user_type_info]
      - [0x812C8, .rodata, autogen/start/gt2_flip_type_info]
      - [0x812D4, rodata, gt2main12]
      - [0x813D4, rodata, gt2main13]
      - [0x81424, rodata, gt2main14]
      - [0x81774, .rodata, autogen/start/gt2_unknown_task14_003]
      - [0x81788, rodata, gt2main15]
      - [0x8179C, .rodata, autogen/start/gt2_unknown_task14_00]
      - [0x8193C, rodata, gt2main16]
      - [0x82078, .rodata, autogen/start/gt2_main_shared_arcadegtrace_func0]
      - [0x8207C, rodata, gt2main17]
      - [0x826A0, .rodata, autogen/start/gt2_main_func53]
      - [0x826A8, rodata, gt2main18]
      - [0x82C14, .rodata, autogen/start/gt2_main_menu_func1]
      - [0x82C18, rodata, gt2main19]
      - [0x82C9C, .rodata, autogen/start/gt2_main_shared_menuarcade_func1]
      - [0x82CA0, rodata, gt2main20]
      - [0x82D24, .rodata, autogen/start/gt2_main_shared_racemenu_func7]
      - [0x82D28, rodata, gt2main21]
      - [0x835F4, data, gt2main]
  - [0x99800]
